mysite/blog/urls.py
# -*-coding:utf-8-*-
__author__ = 'VeyronRomeo',
__author_email__ = 'killni.ma@163.com',
__time__ = '2017\11\14 0014 11:18 '
project = "mysite.blog"
"""
description=
"""
from django.conf.urls import *
#from blog.views import archiveView
import blog.views


urlpatterns = [
    url(r'^$', blog.views.archive),
    url(r'^create/', blog.views.create_blogpost),
    #url(r'^$', archiveView.as_view(), name='posts') #通用视图配置

]

mysite/mysite/urls.py
from django.conf.urls import *
from django.contrib import admin

admin.autodiscover()
# from blog import views
urlpatterns = [
    url(r'^', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^time_trl/', include('time_traveler.urls')),
    url(r'^accounts/', include('users.urls')),

]
"""
urlpatterns = (
               (r'^blog/', include('blog.urls')),
               (r'^admin/', include(admin.site.urls)),
               )
"""

mysite/time_traveler/urls.py
# -*-coding:utf-8-*-
__author__ = 'VeyronRomeo',
__author_email__ = 'killni.ma@163.com',
__time__ = '2017\11\19 0019 11:02 '
project = 'time_traveler'
"""
description=
"""

from django.conf.urls import *

try:
    from time_traveler import views as ui, models
except:
    print 'time_traveler import err'

urlpatterns = [
    url(r'^$', ui.time_index),
    url(r'^create/', ui.user_create),
    url(r'^logined/', ui.user_login),
    url(r'^login/',ui.login),
    url(r'^valide_name/',ui.valide_name),
]

mysite/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.db import models
from django import forms


# Create your models here.
class BolgPost(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    timestamp = models.DateTimeField()

    class Meta:
        ordering = ('-timestamp',)


'''
class BlogPostForm(forms.Form):
    title = forms.CharField(max_length=150)
    body = forms.CharField(widget=forms.Textarea(attrs={'row': 3, 'cols': 60}))
    timestamp = forms.DateTimeField()
'''


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BolgPost
        exclude = ('timestamp',)

mysite/time_traveler/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django import forms


# Create your models here.
class users(models.Model):
    id = models.CharField(max_length=32, primary_key=True)
    uname = models.CharField(max_length=12, db_index=True)
    upassword = models.CharField(max_length=32)
    uuser_email = models.CharField(max_length=32, null=True)
    ufrist_time_password = models.CharField(max_length=32)
    uregistration_time = models.DateTimeField(null=True)
    u_registration_addr = models.CharField(max_length=32, null=True)

    class Meta:
        ordering = ('-uregistration_time',)


class user_form(forms.ModelForm):
    uname = forms.CharField(label=('昵称'), widget=forms.TextInput(attrs={'minlength': '5', 'maxlength': '18'}))
    upassword = forms.CharField(label=("密码"), widget=forms.PasswordInput)
    uuser_email = forms.CharField(label=("邮箱"), widget=forms.EmailInput(attrs={'placeholder': '请输入你的邮箱'}))

    class Meta:
        model = users
        exclude = ('id', 'uregistration_time', 'ufrist_time_password', 'u_registration_addr')
        error_messages = {'uname': {'max_length': ("this writer name is too long")}}

mysite/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from .models import BolgPost, BlogPostForm
from django.http import HttpResponseRedirect
from django.template import loader, RequestContext
from datetime import datetime
from django.shortcuts import render_to_response, render
from django.views.generic.base import TemplateView

# Create your views here.
'''
def year_BolgPost(request, title, body, timestamp):
    context = {'title': title, body: 'body', timestamp : 'timestamp'}
    return render(request, '',context)
'''
'''
#通用视图配置
class archiveView(TemplateView):
    template_name = 'archive.html'
    def get_context_data(self, **kwargs):
        posts = super(archiveView,self).get_context_data(**kwargs)
        posts['latest_articles'] = BolgPost.objects.all()[:5]
        return posts
'''


# 数据模型 模式
def archive(request):
    posts = BolgPost.objects.all()
    # t = loader.get_template('archive.html')
    # c = Context({'posts': posts})
    return render(request, 'index.html', {'posts': posts}, RequestContext(request))
    # 'form': BlogPostForm()
    # return render_to_response('archive.html')

'''

#DRY模式
def create_blogpost(request):
    if request.method == 'POST':
        BolgPost(
            title=request.POST.get('title'),
            body=request.POST.get('body'),
            timestamp=datetime.now(),
        ).save()
    return HttpResponseRedirect('/blog/')
'''


def create_blogpost(request):
    if request.method == 'POST':
        form = BlogPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.timestamp = datetime.now()
            post.save()
    return HttpResponseRedirect('/blog/')

mysite/time_traveler/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.template import RequestContext
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from .models import user_form,users
from datetime import datetime
import hashlib, time


# Create your views here.
def time_index(request):
    return render(request, 'registration.html', {'form': user_form()})

'''
用户
注册处理。
'''
def user_create(request):
    if request.method == 'POST':
        form = user_form(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.id = ceate_Id()

            post.upassword = password_create(post.upassword)
            post.ufrist_time_password = post.upassword
            post.uregistration_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            # post.ulast_time_login_time = datetime.now()
            if request.META.has_key('HTTP_X_FORWARDED_FOR'):
                ip = request.META['HTTP_X_FORWARDED_FOR']
            else:
                ip = request.META['REMOTE_ADDR']
            post.u_registration_addr = ip
            if uname_unque(post.uname):
                pass
            else:
                post.save()
    return HttpResponseRedirect('/time_trl/')



#对name值限制必须以字符开头,函数固定格式valide_field
def valide_name(request):
    if request.method == "GET" and request.GET:
        uname = request.GET['uname']
        if users.objects.filter(uname=uname):
#        if name == id_name:
            uname = "we have a %s" % uname
        else:
            uname = uname
    else:
        uname = "No name"
    result = {"data":uname}
    return JsonResponse(result)


def user_login(request):
    if request.method == 'POST':
        uname = request.POST.get('uname')
        psw = request.POST.get('upasswrod')
        login_verify(uname,psw)
        print uname + psw
    return HttpResponseRedirect('/time_trl/',RequestContext(request))


def login(request):
    return render(request, 'login.html')


def ceate_Id():
    id = hashlib.md5(str(time.clock()).encode('utf-8')).hexdigest()
    return id


def password_create(psw):
    m = hashlib.md5()
    m.update(psw)
    return m.hexdigest()

def login_verify(name,psw):
    user = users.objects.get(uname=name)
    if user is not None:
        password = user.upassword
        print type(password)
        print password

    return 'success'

def uname_unque(name):
    if users.objects.get(uname = name):
        return False
    else:
        return True

mysite/blog/templates/archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>teampleat</title>
</head>
<body>
<form action="/blog/create/" method=post>{% csrf_token %}
    <!--
    Title: <input type=text name="title"><br>
    Body:<textarea name="body" rows="3" cols="60"></textarea><br>
    -->
    <table>{{form}}</table>
    <input type="submit">
</form>
<hr>
    {% for post in posts %}
    <h2>{{post.title|title}}</h2>
    <p>{{post.timestamp}}</p>
    <p>{{post.body}}</p>
    <hr>
    {% endfor%}
</body>
</html>

mysite/blog/templates/base.html
<html>
<body>
<!-- base.html -->
Generic welcome to your web page [login - help - Faq]
<h1>Blog Central</h1>
{% block content %}
{%endblock%}
&copy;2011 your company [About - Contact]
</body>
</html>

mysite/blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
{% extends "base.html" %}
{% block content %}
<form action="/blog/create/" method=post>{% csrf_token %}

    Title: <input type=text name="title"><br>
    Body:<textarea name="body" rows="3" cols="60"></textarea><br>

    <!--<table>{{form}}</table>-->
    <input type="submit">
</form>
<hr>
    {% for post in posts %}
    <h2>{{post.title|title}}</h2>
    <p>{{post.timestamp}}</p>
    <p>{{post.body}}</p>
    <hr>
    {% endfor%}
{% endblock %}
</body>
</html>

mysite/time_traveler/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
ok
</body>
</html>

mysite/time_traveler/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="/time_trl/logined/" method="post">{% csrf_token %}
<ul>
    <li><input name="uname" type="text" placeholder="输入你的账号"></li>
    <li><input name="upasswrod" type="password" placeholder="输入你的密码"></li>
    <li><input type="submit"></li>
</ul>
</form>
</body>
</html>

mysite/time_traveler/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <script type="text/javascript" charset="gbk" module="$" src="https://dlweb.sogoucdn.com/common/lib/jquery/jquery-1.11.0.min.js"></script>
</head>
<body>
<h2>注册账号</h2>
<form action="/time_trl/create/" method=post>{% csrf_token %}
    <table>{{form}}</table>
    <input type="submit">
</form>


<script>
    $(
                function () {
                $("#id_uname").blur(
                    function () {
                        var uname = $("#id_uname").val()
                        $.ajax(
                            {
                                url:"/time_trl/valide_name/",
                                type:"get",
                                data:{"uname":uname},
                                success:function (data) {
                          //          $("#id_name").val("name is exsit")
                                    console.log(data)
                                },
                                error:function (err) {
                                   console.log(err)
                                }
                            }
                        )
                    }
                )
            }
        )
</script>
</body>
</html>